#!/bin/bash


main_init(){
    MIRROR=$(cat $CONFIG | grep '^MIRROR' | cut -d "=" -f2)
    TMP=$(mktemp -dt packages.XXXXXX)
    MIRROR_PKG="$TMP/CHECKSUMS.md5"
    PKG_DIR="/var/log/packages"
    PKG_INSTALL="install_packages.log"
    PKG_REMOTE="remote_packages.log"
    PKG_DIFF="diff_packages.log"
    PKG_UPDATE=$(cat $CONFIG | grep '^PKG_UPDATE' | cut -d "=" -f2)
    BLACKLIST=$(cat $CONFIG | grep '^BLACKLIST' | cut -d "=" -f2)
    ICONS=("/usr/share/icons/oxygen/32x32/status/dialog-information.png" "/usr/share/icons/HighContrast/32x32/status/dialog-information.png")
    INTERVAL=$(cat $CONFIG | grep '^INTERVAL' | cut -d "=" -f2)

    wget -c "${MIRROR}$(echo ${MIRROR} | rev | tr '/' '\n' | head -n 2 | tr '\n' '-' | rev | cut -d '-' -f2 | sed 's:deepstyle:slackware:')/CHECKSUMS.md5" -P $TMP &>/dev/null

    if [[ ! -f ${BLACKLIST} ]]; then 
        touch ${BLACKLIST}
    fi
}




get_name_pkg() {
     [[ ! -z "$1" ]] && echo $(echo "$1" | rev | cut -f4- -d '-' | rev)
}

get_ver_pkg() {
    [[ ! -z "$1" ]] && echo $(echo "$1" | rev | cut -f3 -d '-' | rev)
}

get_rel_pkg() {
    [[ ! -z "$1" ]] && echo $(echo "$1" | rev | cut -f1 -d '-' | tr -cd "[0-9]" | rev)
}

local_packages() {
    # get instaled packages
    ls ${PKG_DIR} | grep -v "upgraded" | sort > ${TMP}/${PKG_INSTALL}
}

remote_packages() {
    # get packages remote
    grep -oP "(?<=\w\/)(.*)(?=\.t.z$)" ${MIRROR_PKG} | sort > ${TMP}/${PKG_REMOTE}
}

diff_packages() {
    # get update packages
    diff -Naur ${TMP}/${PKG_INSTALL} ${TMP}/${PKG_REMOTE} > ${TMP}/${PKG_DIFF}.tmp
    cat ${TMP}/${PKG_DIFF}.tmp | rev | cut -f 4- -d '-' | rev | grep "^[+-]" > ${TMP}/${PKG_DIFF}
#    | grep -oP "(?<=^[\+\-])(.*)(?>-([\d\w]*))$" 
#    | rev | cut -f 4- -d '-' | rev > ${TMP}/${PKG_DIFF}
    
#    grep -v -f ${TMP}/${PKG_DIFF} ${BLACKLIST} > ${TMP}/00
}

find_updates(){
    if [[ ! $(cat ${BLACKLIST} | grep -x $1) ]];then
    if [[ $(cat ${TMP}/${PKG_INSTALL} | awk '{print $3}' | grep -x $1) ]];then
        if [[ ! $(cat ${TMP}/${PKG_INSTALL} | awk '{print $1}' | grep -x $2) ]];then
        echo -e $2 "\t" $3 >> ${PKG_UPDATE}
        let count=${count}+1
        fi
    fi
    fi
}

notify_desktop(){
    if [[ -f ${ICONS[0]} ]]; then  icon=${ICONS[0]}; else icon=${ICONS[1]}; fi

#    notify-send "System Message" "For your system updates available\n<b>${count}</b> packages" -i ${icon}

    for i in $(who | awk '{print $1, $2}' | grep : | uniq);do
        let c=c+1
        if [[ $c == 1 ]];then
            u=$i
        else
            d=$i
        fi
        if [[ $c == 2 ]];then
            c=0
            DISPLAY=$d; XAUTHORITY="$(cat /etc/passwd | grep $u | cut -d ":" -f6)/.Xauthority"; export DISPLAY XAUTHORITY
            su $u -c "notify-send \"System Message\" \"For your system updates available\n<b>${count}</b> packages\" -i ${icon}"
            unset DISPLAY XAUTHORITY
         fi
    done
}


case "$1" in
    "-c")
      CONFIG=${2:-/etc/pun/pun.conf}
      ;;
    *)
      echo "$0 -c <configuration file> &"
      exit 0
      ;;
esac

#exit 0

while true; do

    main_init
    local_packages
    remote_packages
   
    diff_packages

    while read pkg; do
        if [[ ! $(grep -x "$pkg" "$BLACKLIST") && $(grep -x "[+-]$pkg" ${TMP}/${PKG_DIFF} | wc -l) -ge 2 ]]; then
            pkg_install=$(grep "^$pkg" $TMP/$PKG_INSTALL)
            ver=$(get_ver_pkg "$pkg_install")
            rel=$(get_rel_pkg "$pkg_install")

            pkg_remote=$(grep "^$pkg" $TMP/$PKG_REMOTE)
            ver_remote=$(get_ver_pkg "$pkg_remote")
            rel_remote=$(get_rel_pkg "$pkg_remote")

            #echo "up:" $pkg
            #echo $pkg_install $ver $rel "|" $pkg_remote $ver_remote $rel_remote

            [[ $ver != $ver_remote && ! -z $ver_remote ]] && echo "update: $$pkg_install $ver $rel | $pkg_remote $ver_remote $rel_remote" >> l
            [[ $ver == $ver_remote && $rel < $rel_remote && ! -z $rel_remote ]] && echo "upgrade: $pkg_install $ver $rel | $pkg_remote $ver_remote $rel_remote" >> l
        fi
        # remove the load on the CPU
        #sleep 0.2
    done < <((grep "^+" | sed "s/^[+-]//") < ${TMP}/${PKG_DIFF})
#    done < <((rev | cut -f 4- -d '-' | rev) < ${TMP}/${PKG_INSTALL})

exit
    for name_pkg in $(cat ${MIRROR_PKG} | grep asc | awk {'print $2'} | cut -d '/' -f3 | sed 's|.t.z.asc||'); do
        MD5=$(echo ${name_pkg} | md5sum | cut -d ' ' -f1)
        NAME=$(echo ${name_pkg} | tr '-' '\n' | head -n -3 | tr '\n' '-' | sed 's:-$::')
        find_updates ${NAME} ${MD5} ${name_pkg}
    done

    rm -rf $TMP

    if [[ $count -ge 1 ]];then
        notify_desktop
    fi

    unset count

    sleep $INTERVAL
done
