#!/bin/bash


main_init(){
    MIRROR=$(cat $CONFIG | grep '^MIRROR' | cut -d "=" -f2)
    TMP=$(mktemp -dt packages.XXXXXX)
    MIRROR_PKG="$TMP/CHECKSUMS.md5"
    PKG_DIR="/var/log/packages"
    PKG_INSTALL="install_packages.md5"
    PKG_UPDATE=$(cat $CONFIG | grep '^PKG_UPDATE' | cut -d "=" -f2)
    BLACKLIST=$(cat $CONFIG | grep '^BLACKLIST' | cut -d "=" -f2)
    ICONS=("/usr/share/icons/oxygen/32x32/status/dialog-information.png" "/usr/share/icons/HighContrast/32x32/status/dialog-information.png")
    INTERVAL=$(cat $CONFIG | grep '^INTERVAL' | cut -d "=" -f2)

    wget -c "${MIRROR}$(echo ${MIRROR} | rev | tr '/' '\n' | head -n 2 | tr '\n' '-' | rev | cut -d '-' -f2 | sed 's:deepstyle:slackware:')/CHECKSUMS.md5" -P $TMP &>/dev/null

    if [[ ! -f ${BLACKLIST} ]]; then 
        touch ${BLACKLIST}
    fi
}

local_packages(){
    for name_pkg in $(ls ${PKG_DIR}); do
	MD5=$(echo ${name_pkg} | md5sum | cut -d ' ' -f1)
	NAME=$(echo ${name_pkg} | tr '-' '\n' | head -n -3 | tr '\n' '-' | sed 's:-$::')
	echo -e ${MD5} "\t" ${name_pkg} "\t" ${NAME} >> ${TMP}/${PKG_INSTALL}
    done
}

find_updates(){
    if [[ ! $(cat ${BLACKLIST} | grep -x $1) ]];then
	if [[ $(cat ${TMP}/${PKG_INSTALL} | awk '{print $3}' | grep -x $1) ]];then
	    if [[ ! $(cat ${TMP}/${PKG_INSTALL} | awk '{print $1}' | grep -x $2) ]];then
		echo -e $2 "\t" $3 >> ${PKG_UPDATE}
		let count=${count}+1
	    fi
	fi
    fi
}

rename_log(){
    if [[ -f  ${PKG_UPDATE} ]]; then 
        mv ${PKG_UPDATE} "${PKG_UPDATE}_$(date +%Y%m%d%H%M%S)"
    fi
}

notify_desktop(){
    if [[ -f ${ICONS[0]} ]]; then  icon=${ICONS[0]}; else icon=${ICONS[1]}; fi

#    notify-send "System Message" "For your system updates available\n<b>${count}</b> packages" -i ${icon}

    for i in $(who | awk '{print $1, $2}' | grep : | uniq);do
        let c=c+1
        if [[ $c == 1 ]];then
            u=$i
        else
            d=$i
        fi
        if [[ $c == 2 ]];then
            c=0
            DISPLAY=$d; XAUTHORITY="$(cat /etc/passwd | grep $u | cut -d ":" -f6)/.Xauthority"; export DISPLAY XAUTHORITY
            su $u -c "notify-send \"System Message\" \"For your system updates available\n<b>${count}</b> packages\" -i ${icon}"
            unset DISPLAY XAUTHORITY
         fi
    done
}


case "$1" in
    "-c")
      CONFIG=${2:-/etc/pun/pun.conf}
      main_init
      ;;
    *)
      echo "$0 -c <configuration file> &"
      exit 0
      ;;
esac

#exit 0

while true; do

    main_init
    rename_log
    local_packages

    for name_pkg in $(cat ${MIRROR_PKG} | grep asc | awk {'print $2'} | cut -d '/' -f3 | sed 's|.t.z.asc||'); do
        MD5=$(echo ${name_pkg} | md5sum | cut -d ' ' -f1)
        NAME=$(echo ${name_pkg} | tr '-' '\n' | head -n -3 | tr '\n' '-' | sed 's:-$::')
        find_updates ${NAME} ${MD5} ${name_pkg}
    done

    rm -rf $TMP

    if [[ $count -ge 1 ]];then
        notify_desktop
    fi

    unset count

    sleep $INTERVAL
done
